services:
#    kit_crypt.example:
#        class: Kit\CryptBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_crypt.openssl:
        class: Kit\CryptBundle\Service\OpensslService
        arguments: ["%kit_crypt.clients%"]