services:
#    kit_crypt.example:
#        class: Kit\CryptBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_crypt.openssl:
        class: Kit\CryptBundle\Service\OpensslService
        autowire: true
        public: true
        arguments:
            $clients: "%kit_crypt.clients%"
    Kit\CryptBundle\Service\OpensslService: '@kit_crypt.openssl'