services:
#    kit_crypt.example:
#        class: Kit\CryptBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    Kit\CryptBundle\Service\OpensslService:
        autowire: true
        arguments:
            $clients: "%kit_crypt.clients%"